[general]
rpc_endpoint = "http://localhost:8545"

[account.teth]
address = "GU7NS9xCwgNPiAdJ69iusFrRfawjDDPjeMBovhV1d4kn"

[account.usdc]
address = "AKEWE7Bgh87GPp171b4cJPSSZfmZwQ3KaqYqXoKLNAEE"

[account.usdt]
address = "CEBP3CqAbW4zdZA57H2wfaSG1QNdzQ72GiQEbQXyW9Tm"

[account.sol]
address = "BeRUj3h7BqkbdfFU7FBNYbodgf8GCHodzKvF9aVjNNfL"

[program.orca_whirlpool]
address = "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc"

[program.invariant]
address = "iNvTyprs4TX8m6UeUEkeqDFjAL9zRCRWcexK9Sd4WEU"
